Metadata-Version: 2.1
Name: wrap-exception
Version: 0.0.2
Summary: Baiscally just an Exception class that retains traceback information
Home-page: https://github.com/langal/python2_wrapped__exception
Author: Alex Lang
Author-email: alex.lang@gmail.com
License: UNKNOWN
Platform: UNKNOWN
Classifier: Programming Language :: Python :: 2
Classifier: License :: OSI Approved :: MIT License
Classifier: Operating System :: OS Independent
Requires-Python: >=2.7
Description-Content-Type: text/markdown

# python2_wrapped__exception

This is basically an Exception class that would be used to wrap raised Exceptions.

The common use case is when one wants to present a custom exception class to a downstream caller.

One would typically do this:

<pre>
<code>
try:
    doStuffTHatTHrowsAnException()
except Exception as e:
    raise MyCustomException(e.message)
</code>
</pre>
However, the above code causes the execution stack at the time of the first exception to be lost.

The WrappedException allows us to do this:


<pre>
<code>
try:
    doStuffTHatTHrowsAnException()
except Exception:
    WrappedException.throw()
</code>
</pre>

Callers can now catch "WrappedException" and still have the original execution stack.

Alternatively, they can do this:

<pre>
<code>
try:
    doStuffTHatTHrowsAnException()
except Exception as e:
    WrappedException(e.message, another_parameter, etc.).throw()
</code>
</pre>

As WrappedException would typically be subclassed with a "business" exception.





